name: Melos Version and Release
on:
  push:
    branches: [ $default-branch ]
jobs:
  call-melos-version:
    uses: appbrewingcompany/.github/.github/workflows/melos-version.yml@main
    permissions:
      contents: write
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
