name: Version and Release

on:
  workflow_call:
    secrets:
      PRIVATE_REPO_TOKEN:
        required: true

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Fetch FVM config
        id: fvm-config-action
        uses: kuhnroyal/flutter-fvm-config-action@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true

      - name: Setup Git User & Auth
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global url."https://${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/".insteadOf "git@github.com:"

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap Melos
        run: melos bootstrap

      - name: Version Packages
        run: melos version -a --yes

      - name: Push Version Commit & Tags
        run: git push --follow-tags
